name: "Pull Result Artifacts"

on:
  schedule:
    # Every night at midnight
    - cron:  0 0 * * *

jobs:
  find-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make artifact directory
        run: mkdir -p ./artifacts

      - name: Get Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_REPOSITORY: "buildsi/build-abi-containers"          

          # Check for the last 2 days
          INPUT_DAYS: 2
        run: |
          pip install -r requirements.txt
          python get_artifacts.py
